

server:
  port: 8091
  servlet:
    contextPath: /time-sheet

spring:
  application:
    name: time-sheet
  datasource:
    url: jdbc:postgresql://maoz-developer.com:5444/timesheet
    username: timesheetapp
    password: timesheetapppassword2020
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    validation-query: select 1 from dual
    test-on-borrow: true
    removeAbandoned: true
    removeAbandonedTimeout: 10

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL94Dialect

api:
  IAM: https://dev.priorsolution.co.th/iam/v2/