create table attendance (attendance_id bigint generated by default as identity, date timestamp, site varchar(255), task varchar(255), time_in varchar(255), time_out varchar(255), project_code varchar(255), user_code varchar(255), primary key (attendance_id))
create table project (project_code varchar(255) not null, date timestamp, description varchar(255), project_name varchar(255), user_code_supervisor varchar(255), primary key (project_code))
create table TIME_SHEET_DB.user_ms (user_code varchar(255) not null, primary key (user_code))
create table TIME_SHEET_DB.user_profile_ms (user_profile_id bigint generated by default as identity, address varchar(255), age integer, birthday timestamp, firstname varchar(255), lastname varchar(255), position varchar(255), site varchar(255), user_code varchar(255), primary key (user_profile_id))
create table TIME_SHEET_DB.user_project (date timestamp, task varchar(255), project_code varchar(255) not null, user_code varchar(255) not null, primary key (project_code, user_code))
alter table attendance add constraint FKioynp87tkop2q76fqy8qnklct foreign key (project_code) references project
alter table attendance add constraint FK27fe2ok4duu0k7n8jr1odik5a foreign key (user_code) references user_ms
alter table user_profile_ms add constraint FK4jm8pocp0cif20mind4txeyg4 foreign key (user_code) references user_ms
alter table user_project add constraint FKcejankxp9o93ng2s4hja9726b foreign key (project_code) references project
alter table user_project add constraint FKtp35y3ru4i5potxsaelcsocv9 foreign key (user_code) references user_ms
create table TIME_SHEET_DB.attendance (attendance_id  bigserial not null, date timestamp, site varchar(255), task varchar(255), time_in varchar(255), time_out varchar(255), project_code varchar(255), user_code varchar(255), primary key (attendance_id))
create table TIME_SHEET_DB.project (project_code varchar(255) not null, date timestamp, description varchar(255), project_name varchar(255), user_code_supervisor varchar(255), primary key (project_code))
create table TIME_SHEET_DB.user_ms (user_code varchar(255) not null, primary key (user_code))
create table TIME_SHEET_DB.user_profile_ms (user_profile_id  bigserial not null, address varchar(255), age int4, birthday timestamp, firstname varchar(255), lastname varchar(255), position varchar(255), site varchar(255), user_code varchar(255), primary key (user_profile_id))
create table TIME_SHEET_DB.user_project (date timestamp, task varchar(255), project_code varchar(255) not null, user_code varchar(255) not null, primary key (project_code, user_code))
alter table TIME_SHEET_DB.attendance add constraint FKioynp87tkop2q76fqy8qnklct foreign key (project_code) references time_sheet_db.project
alter table TIME_SHEET_DB.attendance add constraint FK27fe2ok4duu0k7n8jr1odik5a foreign key (user_code) references time_sheet_db.user_ms
alter table TIME_SHEET_DB.user_profile_ms add constraint FK4jm8pocp0cif20mind4txeyg4 foreign key (user_code) references time_sheet_db.user_ms
alter table TIME_SHEET_DB.user_project add constraint FKcejankxp9o93ng2s4hja9726b foreign key (project_code) references time_sheet_db.project
alter table TIME_SHEET_DB.user_project add constraint FKtp35y3ru4i5potxsaelcsocv9 foreign key (user_code) references time_sheet_db.user_ms
